### PR TITLE
Null references and outputs updated

### PR DESCRIPTION
**Pull request by brianmccarty**
# Changed references null comparisons.
The way powershell handles $null in a comparison can allow for two $null values to become true.  fix is to place $null first in comparisons.
help about_Comparison_Operators

   When the input to an operator is a scalar value, comparison operators
   return a Boolean value. When the input is a collection of values, the
   comparison operators return any matching values. If there are no matches
   in a collection, comparison operators do not return anything.

   The exceptions are the containment operators (-Contains, -NotContains),
   the In operators (-In, -NotIn), and the type operators (-Is, -IsNot),
   which always return a Boolean value.
```powershell
<value_to_compare> -eq $null
$null -eq <value_to_compare>
```

# Changed the sending of output to null references to use [void] cast type.  This appears cleaner and is faster processing in the Powershell engine.

### CODE REVIEW

**Comment by adrianwells** [comment]
@brianmccarty thank you for this effort. It looks like a good optimization. Will plan to review/test.

**Comment by adrianwells** [comment]
@CalebAlbers and @ecspresso, Hello. My basic testing looks good so will plan to merge this soon unless you have other thoughts?

**Comment by CalebAlbers** [comment]
@adrianwells I'm completely fine with that. The general concept is referred to as [Yoda Conditions](https://en.wikipedia.org/wiki/Yoda_conditions), and I'm a fan of it in general from back in my embedded programming days.

Feel free to squash and merge. I'll update the module in PS Gallery accordingly. Side note, I'm going to add some form of linting to the project to avoid any goofy diffs that just contain stuff like newline differences or trailing spaces.

Thanks for the contributions, @brianmccarty !

**Comment by adrianwells** [comment]
@CalebAlbers, OK. Why the squash for the merge?

**Comment by CalebAlbers** [comment]
There are two commits in this pull request, so squashing them together will drop both into a single commit to master. Alternatively, doing a merge commit where both commits make it to master work, too. I don't really have a preference, given this project isn't at a scale where not squashing will cause too many problems.

**Comment by adrianwells** [comment]
@CalebAlbers , thanks, didn't know if there was a specific reason. I agree merge commit can work and believe it's OK here. Will get the version number updated as part of this PR.

**Comment by adrianwells** [comment]
@CalebAlbers please update the module in PS Gallery. If there's a way to co-publish, would like to know more to help move these forward. Thank you.

**Pull request merged**
