### PR TITLE
Set the body parameter correctly.

### PR DESCRIPTION
**Pull request by lwhitelock**
Sets the body parameter in the get requests so it actually works

### CODE REVIEW

**Comment by lwhitelock** [comment]
There is no need to be petty this is a genuine fix to an issue with the module!

**Comment by davidhaymond** [comment]
Correct me if I'm wrong, but the code in question is making a GET request, which do not have bodies. Does this PR fix a specific issue you are having?

**Comment by lwhitelock** [comment]
> Correct me if I'm wrong, but the code in question is making a GET request, which do not have bodies. Does this PR fix a specific issue you are having?

I know normally they don't but in this case IT Glue wants all the filters passed in the body of the get request. Look at line 76 onwards all the attributes are built into the body parameter. This fixes the filters for the request. I ended up forking this module and publishing ITGlueAPIv2 just to get a fix for filtering on Get-ITGlueFlexibleAssetFields to work.

**Comment by ecspresso** [comment]
> > Correct me if I'm wrong, but the code in question is making a GET request, which do not have bodies. Does this PR fix a specific issue you are having?
> 
> I know normally they don't but in this case IT Glue wants all the filters passed in the body of the get request. Look at line 76 onwards all the attributes are built into the body parameter. This fixes the filters for the request. I ended up forking this module and publishing ITGlueAPIv2 just to get a fix for filtering on Get-ITGlueFlexibleAssetFields to work.

I know this was the case a few years ago and maybe it still works, but will in the future? Looking at their documentation now, their examples have the filter and pagination parameters in the URL.

https://support.itglue.com/hc/en-us/articles/360004934397-Sorting-and-filtering-in-the-IT-Glue-API
https://support.itglue.com/hc/en-us/articles/360004934057-Pagination-in-the-IT-Glue-API

**Pull request merged**
