### PR TITLE
Fix for #46

### PR DESCRIPTION
**Pull request by ecspresso**
`-body $body` was missing, filtering was not working as a result.

### CODE REVIEW

**Comment by ecspresso** [comment]
Is `[Parameter(ParameterSetName = 'update', Mandatory = $true)]` needed? Should it not be removed since we are removing the object and not changing it.

**Comment by adrianwells** [comment]
@ecspresso Thank you for the PR.  Hope to merge it soon.  Do not yet have an answer to your question regarding if `[Parameter(ParameterSetName = 'update', Mandatory = $true)] ` is needed, if you have more thoughts, please share.

**Comment by ecspresso** [comment]
@adrianwells  I updated the function `Remove-ITGluePasswords` to reflect what I had in mind. When removing a single password, only ID can be supplied. It seems IT Glue ignores the empty body also supplied, so this does not have to be handled for now.

**Comment by adrianwells** [comment]
@ecspresso, Great!  Do you mind incrementing the `Module version` in `ITGlueAPI/ITGlueAPI.psd1` as part of this PR to help with versioning? Trying to use versioning and releases to help tracking the efforts.

**Comment by ecspresso** [comment]
@adrianwells I changed to version 2.0.4, is this correct?

**Comment by adrianwells** [comment]
@ecspresso, yes that looks good!  Thank you.

**Pull request merged**
