### PR TITLE
Added missing filter parameter

### PR DESCRIPTION
**Pull request by ecspresso**
filter[group_id] was missing from Get-ITGlueOrganizations, added the parameter and check.

### CODE REVIEW

**Comment by adrianwells** [comment]
@ecspresso, Hello.  Thanks.  Do you mind incrementing the `Module version` again in `ITGlueAPI/ITGlueAPI.psd1` as part of this PR to help with versioning? Trying to use versioning and releases to help with tracking.  Also curious, is this related to an existing issue or a new fix?

**Comment by ecspresso** [comment]
@adrianwells It is a new fix, I noticed it was missing when looking at the documentation. Do you want me to create a bug report and relate it to this PR?

**Comment by adrianwells** [comment]
@ecspresso, I think it is helpful to folks to have an issue related to a pull request to further communicate the reason behind it if you do not mind, however, I do not want to create extra work.

**Comment by ecspresso** [comment]
This PR now addresses the issue in #60.

Let me know if there is anything else I should. 😃

**Comment by adrianwells** [comment]
Thanks @ecspresso for playing along!  @CalebAlbers I plan to merge this soon unless you have another approach?

**Comment by CalebAlbers** [comment]
I think we're good to go here. I'll squash and merge, and then push to the Powershell gallery today.

**Pull request merged**
